# Generated by Django 5.0.4 on 2024-04-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=15)),
                ('food_img_uri', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
