# Generated by Django 5.0.4 on 2024-04-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_address_user_category_user_fees_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exp_date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
