# Generated by Django 5.0.4 on 2024-04-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_poll_1', models.CharField(max_length=200)),
                ('morning_poll_1_value', models.IntegerField(default=0)),
                ('morning_poll_2', models.CharField(max_length=200)),
                ('morning_poll_2_value', models.IntegerField(default=0)),
                ('evening_poll_1', models.CharField(max_length=200)),
                ('evening_poll_1_value', models.IntegerField(default=0)),
                ('evening_poll_2', models.CharField(max_length=200)),
                ('evening_poll_2_value', models.IntegerField(default=0)),
            ],
        ),
    ]
