# Generated by Django 5.0.4 on 2024-04-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fooditem_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=200, null=True)),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=200, null=True)),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
    ]
