# Generated by Django 5.0.4 on 2024-04-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_histroy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200, null=True)),
                ('date', models.CharField(max_length=15)),
            ],
        ),
    ]
